RootWidget:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            id: screen

            MyVideoPlayer:
                id: video_player

        BoxLayout:
            id: menu
            size_hint: None, None
            size : 100, 50
            orientation: 'horizontal'
            Button:
                text: 'start'
                on_release: root.on_btn_start()
            Button:
                text: 'stop'
                on_release: root.on_btn_stop()
